### ISSUE TITLE
No toolset-compatible output option

### ISSUE THREAD

**Issue by DaloLorn** [kevL/yata#1]
I recently picked this up as an upgrade over using Sublime for my 2DA work. Great tool, immediately dropped all other modes of 2DA editing in its favor.

Eeeexcept it turns out it's not great for my use case. I'm a junior dev on the Baldur's Gate: The Sword Coast Chronicles PW over in NWN2, and don't have the authority to tell everyone to use it... but some of my teammates use the NWN2 toolset, which prefers to output right-aligned 2DAs. Yata's aligned output is left-aligned, with no option to change this, which means that any file I touch in Yata is off-limits to anyone not using Yata unless they want to commit a whole new file (as far as any version control system is concerned).

Could you maybe add an option for `alignoutput` to format the file as if generated by the toolset? Pretty please? It'll take ages to convert all my peers to the glory of Yata... :cry:

**Comment by kevL** [comment]
thanks for the kudos

i found their Save() routine in OEIShared.dll (using ILSpy)

`OEIShared.IO.TwoDA.TwoDAFile.Save(string)`

and am in the process of adapting it into Yata ... will see how it goes

/no guarantees

**Comment by kevL** [comment]
huh looks like i got it

next release will accept Setting "alignoutput=electron"

but i did only minor testing: Actions.2da (output w/ toolset against output by Yata)


I want to finish up Info/Input for BaseItems.2da before next version ... its a bit more extensive than i first thought so it'll be a few days or a week+

**Comment by kevL** [comment]
@DaloLorn do you want a testbuild

to put it through some paces and check if it comes out right ..?

**Comment by DaloLorn** [comment]
Sure! It shouldn't take too long to see if it works the way I'm hoping.

TBH, I considered opening a pull request for it myself, but I suspected it would be faster for you to implement a new AO setting than for me to puzzle out enough about Yata's codebase to do it myself. (Plus I'd have to *guess* at what the toolset output looks like, whereas some of your posts on the NWNVault forums suggested you'd had some experience with this sort of thing before.)

Definitely sounds like I was right, considering how quickly this all happened! 😀

**Comment by kevL** [comment]
aye, am just getting some warnings when such a file loads about "extraneous whitespace" that i want to bypass (iff `AoElectron` is true).

The code in the toolset DLLs isn't pretty ... as i adapted their routine to yata-code, I end up adding comments like

// indent col-fields (add another space, just because)

the arbitrariness of their code makes me shake my head /shrug/ but im used to it ... in other words, discovering the pattern they used to write 2da files would basically be impossible without disassembling their routine ...

ps. will link to a build here tomorrow once i get that warning out of the way,

**Comment by kevL** [comment]
[Yata_220714_5140.7z](https://drive.google.com/file/d/1Hc8waYex3-7PxtO9I-GgKdN4YX-BJ2wh/view?usp=sharing)
https://drive.google.com/file/d/1Hc8waYex3-7PxtO9I-GgKdN4YX-BJ2wh/view?usp=sharing

heh. I compared the output of my Placeables.2da (~25000 rows) from the toolset against yata with "alignoutput=electron" in Settings.Cfg ...

Winmerge said "files are identical" (whitespace comparison on)

but pls check it out, there could be additional quirks if for example "clearquotes=true" ... etc etc

**Comment by DaloLorn** [comment]
TortoiseSVN also reports no changes to commit (tested on BG's feat.2da), so that checks out. Aside from a few cosmetic tweaks (I set my font to a 9pt Consolas), my config file's basically blank, so... I think that's it, then. On closer inspection, I notice that some of our other 2DAs *don't* match toolset output, but our nonexistent style guide is neither here nor there. 😂

Looks good to me, at any rate!

**Comment by kevL** [comment]
ok
