### ISSUE TITLE
Hard-coded paths in postbuild instructions

### ISSUE THREAD

**Issue by Bebop182** [kevL/yata#3]
Release postbuild instructions:
copy /y C:\GIT\yata\bin\Release\yata.exe "C:\Program Files\Yata\"
copy /y C:\GIT\yata\bin\Release\yata.exe "C:\GIT\yata\dist\Yata\"
copy /y C:\GIT\yata\ReadMe.txt "C:\Program Files\Yata\"
copy /y C:\GIT\yata\ReadMe.txt "C:\GIT\yata\dist\Yata\"

Better to use alias like "$(TargetDir)", "$(ProjectName)" or "$(SolutionDir)". Otherwise the project won't compile in release mode if the path doesn't match. Also ReadMe.txt can be added as a project resource and be configured to be copied along at the output dir.

**Comment by kevL** [comment]
thanks for the tips, Bebop
I'll remove those postbuild instructions (and probably just use a small batchfile to shunt those files around on my HD).

standby ... [ok should be gtg]
